theme: jekyll-theme-slate
title: Cómo mejorar el testing de tu backend
logo: /assets/img/logo.png
description: Recursos de la formación impartida los días 16 y 17 de marzo de 2021
show_downloads: false
